name: "Poetry validation"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      
      - name: Set up poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Sync dependencies
        run: poetry install --with dev

      - name: Make distributions 
        run: poetry build 

      